version: 0.2

phases:
  install:
    runtime-version:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Maven Build Completed
      - mvn package

artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes

