#file:
#  upload-dir: D:\\JavaProjects\\zxc\\images\\

server:
  port: 8080
#
#email:
#  address: basearchetype@gmail.com
spring:
  datasource:
    url: jdbc:postgresql://qreceipt.ctwghsf2rmhb.us-east-1.rds.amazonaws.com:5432/
    username: postgres
    password: t3y445qjp0ujmBoU0ECk

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 15MB
#      max-request-size: 15MB
#
#  mail:
#    host: imap.gmail.com
#    port: 465
#    username: xxx
#    password: xxx
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#          starttls:
#            required: true
#          auth: true
#  flyway:
#    baseline-on-migrate: true
#    sql-migration-prefix: "Q"
#    locations: classpath:/db/migration/postgresql
#    table: xxx