spring:
  application:
    name: qreceipt
  config:
    import: "optional:consul:"
  cloud:
    consul:
      binder:
        enabled: true
      scheme: ${consul_scheme:http}
      host: ${consul_host:45.148.31.152}
      port: ${consul_port:8500}
      config:
        format: yaml
      discovery:
        preferIpAddress: true
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
