#file:
#  upload-dir: D:\\JavaProjects\\zxc\\images\\

server:
  port: 8080

email:
  address: basearchetype@gmail.com
spring:
  datasource:
    url: jdbc:postgresql://45.148.31.152:5432/qreceipt
    username: postgres
    password: postgres

  jpa:
    #show-sql: true # commend it
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    username: reddit404error@gmail.com
    password: gTsvOF4Pa6M3mU2G

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    baseline-on-migrate: true
    sql-migration-prefix: "Q"
    locations: classpath:/db/migration/postgresql
    table: qreceipt_flyway_schema
