name: Docker Build and Deploy
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: qreceipt:latest
          run: |
            sudo docker stop qreceipt || true
            sudo docker rm qreceipt || true
            sudo docker run -d -p 8080:8080 --name qreceipt --restart always qreceipt:latest
